services:
  reverse-proxy:
    image: traefik:v3.5
    restart: unless-stopped
    command:
      - "--api"
      - "--api.insecure=true"
      - "--api.dashboard=true"

      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"

      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=email@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"

      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"

      - "--log=true"
      - "--log.filepath=/var/log/traefik.log"
      - "--log.level=DEBUG"
      - "--accesslog.filepath=/var/log/access_traefik.log"

    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      # listens to all the docker socket, so it reads all docker services
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik
      - ./traefik/log:/var/log
    networks:
      - obsidian
  couchserver:
    image: couchdb:latest
    restart: unless-stopped
    #deploy:
    #  mode: replicated
    #  replicas: 3
    networks:
      - obsidian
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.couchserver.entrypoints=websecure"
      - "traefik.http.routers.couchserver.tls=true"
      - "traefik.http.routers.couchserver.tls.certresolver=myresolver"
      - "traefik.http.routers.couchserver.rule=Host(`MY_HOST`)"

      - "traefik.http.services.couchserver.loadbalancer.server.port=5984"

      - "traefik.docker.network=obsidian"
    env_file:
      - .env
    volumes:
      - ./data:/opt/couchdb/data
      - ./etc:/opt/couchdb/etc/local.d

volumes:
  data: {}
  etc: {}
  letsencrypt: {}

networks:
  obsidian:
    # external: true
    driver: bridge
